package com.taufiq.core.utils

object UtilConstant {
    const val TOKEN_EXAMPLE =
        "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImNvbS5hZWouYXVyZWwiLCJpZCI6ImQyZTQ2MjdjLTU5MjgtNDJhZi05YTQzLTk5YjRkMzYyNTBlYiIsImV4cCI6MTY0OTQyNzA0NSwiaGFzaCI6InJKUExyT0ZOWHdtdE1XcUtWV1R6UUE9PSJ9.MCYqBZVQr4vJE1vPOvpI22AxLq1imYbiIfTRaExlbh4Wn-CIgxPLyyzHHv5zKp7p6XlUDapHfqhhd4ocSHs7-Q"
}